[general]
# Start Satty in fullscreen mode
fullscreen = true
# Exit directly after copy/save action
early-exit = true
corner-roundness = 12
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"
# Increase or decrease the size of the annotations
annotation-size-factor = 0.40
# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
output-filename = "~/Pictures/screenshots/screen-%Y-%m-%d_%H:%M:%S.png"

actions-on-enter = ["save-to-file"]
actions-on-right-click = ["exit"]
actions-on-escape = ["exit"]

# # Font to use for text annotations
# [font]
# family = "Roboto"
# style = "Bold"


# custom colours for the colour palette
[color-palette]
palette = [
    "#ef476f",
    "#f78c6b",
    "#ffd166",
    "#06d6a0",
    "#118ab2",
    "#073b4c",
]

custom = [
    "#00ffff",
    "#a52a2a",
    "#dc143c",
    "#ff1493",
    "#ffd700",
    "#008000",
]

