# ============================================================================
# ~/.config/starship/config.toml - Starship Prompt Configuration
# ============================================================================
add_newline = false

[directory]
format = "[$path]($style) "
style = "bold #FFC44F"
truncation_length = 1
fish_style_pwd_dir_length = 3

[character]
success_symbol = "[➜](bold green) "
error_symbol   = "[✖](bold red) "

[git_branch]
format = "[· $branch ·]($style) "
style = "bold #fcdd9f"

[package]
disabled = true

[time]
disabled = true

[hostname]
disabled = true

[jobs]
disabled = true
